[package]
# Semantic Versionning is used: https://semver.org/
version = "1.0.0"

# The title and description fields are primarily for displaying extension info in UI
title = "CloudArchitect.LIVE - Meta Cloud Explorer (Azure edition)"
description="A scene authoring tool to help visualize your Azure Infrastructure in your own private Onmiverse!"

# Path (relative to the root) or content of readme markdown file for UI.
readme  = "docs/README.md"

# URL of the extension source repository.
repository = "https://github.com/CloudArchitectLive/AzureCloudExplorer"

# One of categories for UI.
category = "Cloud"

# Keywords for the extension
keywords = ["Azure", "CloudArchitect.live", "Meta Cloud Explorer (Azure)", "scene authoring tools"]

# Use omni.ui to build simple UI
[dependencies]
"omni.kit.uiapp" = {}

[python.pipapi]
requirements = [
     "pandas",
     "numpy",
     "azure-mgmt-resource",
     "azure-mgmt-core"
]

# Main python module this extension provides, it will be publicly available as "import cloud.explorer.azure".
[[python.module]]
name = "cloud.explorer.azure"
